### ISSUE TITLE
Crash after opening the app

### ISSUE THREAD

**Issue by Marocco2** [ClassicOldSong/moonlight-android#37]
### Describe the bug

Crash upon launching the app. It occured in the latest version.

### Steps to reproduce

Open the app

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

No

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android 14 (GrapheneOS)

### Device model

Pixel 8 Pro 

### Server PC OS version

Windows 11 23H2

### Relevant log output

```Shell
type: crash
osVersion: google/husky/husky:14/AP2A.240905.003/2024101200:user/release-keys
flags: dev options enabled
package: com.limelight.noir:28
process: com.limelight.noir
processUptime: 100 + 259 ms
installer: dev.imranr.obtainium

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.limelight.noir/com.limelight.PcView}: java.lang.ClassCastException: com.bytehamster.lib.preferencesearch.SearchPreference cannot be cast to android.preference.Preference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.ClassCastException: com.bytehamster.lib.preferencesearch.SearchPreference cannot be cast to android.preference.Preference
	at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:49)
	at android.preference.GenericInflater.rInflate(GenericInflater.java:497)
	at android.preference.GenericInflater.inflate(GenericInflater.java:334)
	at android.preference.GenericInflater.inflate(GenericInflater.java:271)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:343)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:670)
	at android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:629)
	at com.limelight.PcView.initializeViews(Unknown Source:20)
	at com.limelight.PcView.completeOnCreate(Unknown Source:36)
	at com.limelight.PcView.onCreate(Unknown Source:51)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 15 more
```
```


### Additional context

_No response_

**Comment by ClassicOldSong** [comment]
Fixed: https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-artemis-241013
